// Generated by CoffeeScript 1.12.6
(function() {
  var HOMEDIR, LIB, LIB_COV, LIB_DIR, fs, index, path, should;

  should = require('should');

  fs = require('fs');

  path = require('path');

  HOMEDIR = path.join(__dirname, '..');

  LIB_COV = path.join(HOMEDIR, 'lib-cov');

  LIB = path.join(HOMEDIR, 'lib');

  LIB_DIR = fs.existsSync(LIB_COV) ? LIB_COV : LIB;

  index = require(path.join(LIB_DIR, 'index'));

  describe("index", function() {
    it("exports Util and Sequencer", function(done) {
      index.Util.should.exist;
      index.Sequencer.should.exist;
      return done();
    });
    it("exports Stopwatch", function(done) {
      index.Stopwatch.should.exist;
      return done();
    });
    it("exports config", function(done) {
      index.config.should.exist;
      return done();
    });
    it("exports IOUtil", function(done) {
      index.IOUtil.should.exist;
      return done();
    });
    it("exports WorkQueue", function(done) {
      index.WorkQueue.should.exist;
      return done();
    });
    it("exports StringUtil", function(done) {
      index.StringUtil.should.exist;
      return done();
    });
    it("exports ZipUtil", function(done) {
      index.ZipUtil.should.exist;
      return done();
    });
    it("exports LogUtil", function(done) {
      index.LogUtil.should.exist;
      index.LogUtil.init.should.exist;
      index.LogUtil.LogUtil.should.exist;
      return done();
    });
    it("exports FileLogger", function(done) {
      index.FileLogger.should.exist;
      return done();
    });
    it("exports AsyncUtil", function(done) {
      index.AsyncUtil.should.exist;
      index.Sequencer.should.exist;
      index.Util.for_each_async.should.exist;
      index.Util.procedure.should.exist;
      return done();
    });
    return it("exports S3Model", function(done) {
      index.S3Model.should.exist;
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=test-index.js.map
