// Generated by CoffeeScript 1.12.6
(function() {
  var HOMEDIR, LIB, LIB_COV, LIB_DIR, exported, file, fn, fs, i, j, k, l, len, len1, len2, len3, m, path, ref, ref1, ref2, sources, v;

  fs = require('fs');

  path = require('path');

  HOMEDIR = path.join(__dirname, '..');

  LIB_COV = path.join(HOMEDIR, 'lib-cov');

  LIB = path.join(HOMEDIR, 'lib');

  LIB_DIR = fs.existsSync(LIB_COV) ? LIB_COV : LIB;

  sources = ['async-util', 'config', 'file-util', 'io-util', 'net-util', 'object-util', 'stopwatch', 's3-model', 'string-util', 'util', 'work-queue', 'zip-util', 'log-util', 'file-logger'];

  for (i = 0, len = sources.length; i < len; i++) {
    file = sources[i];
    exported = require(path.join(LIB_DIR, file));
    for (k in exported) {
      v = exported[k];
      exports[k] = v;
    }
  }

  ref = ["read_stdin_sync", "load_json_file_sync", "load_json_stdin_sync"];
  for (j = 0, len1 = ref.length; j < len1; j++) {
    fn = ref[j];
    exports.Util[fn] = exports.FileUtil[fn];
  }

  ref1 = ['trim', 'isnt_blank', 'is_blank', 'blank_to_null', 'truncate', 'escape_for_json', 'escape_for_regexp', 'truthy_string', 'falsey_string', 'lpad', 'lpad_string', 'rpad', 'rpad_string'];
  for (l = 0, len2 = ref1.length; l < len2; l++) {
    fn = ref1[l];
    exports.Util[fn] = exports.StringUtil[fn];
  }

  ref2 = ['for_async', 'for_each_async', 'fork', 'throttled_fork', 'procedure'];
  for (m = 0, len3 = ref2.length; m < len3; m++) {
    fn = ref2[m];
    exports.Util[fn] = exports.AsyncUtil[fn];
  }

}).call(this);

//# sourceMappingURL=index.js.map
