// Generated by CoffeeScript 1.12.6
(function() {
  var DEBUG, IOUtil, fs, ref, ref1, request;

  fs = require('fs');

  request = require('request');

  DEBUG = (/(^|,)inote-?util($|,)/i.test(typeof process !== "undefined" && process !== null ? (ref = process.env) != null ? ref.NODE_DEBUG : void 0 : void 0)) || (/(^|,)IOUtil($|,)/.test(typeof process !== "undefined" && process !== null ? (ref1 = process.env) != null ? ref1.NODE_DEBUG : void 0 : void 0));

  IOUtil = (function() {
    function IOUtil() {}

    IOUtil.pipe_to_buffer = function(readable_stream, callback) {
      var data, length;
      data = [];
      length = 0;
      readable_stream.on('data', function(chunk) {
        if (chunk != null) {
          data.push(chunk);
          return length += chunk.length;
        }
      });
      readable_stream.on('error', function(err) {
        return callback(err);
      });
      return readable_stream.on('end', function() {
        return callback(null, Buffer.concat(data));
      });
    };

    IOUtil.pipe_to_file = function(readable_stream, dest, options, callback) {
      var out;
      if ((options != null) && typeof options === 'function' && (callback == null)) {
        callback = options;
        options = null;
      }
      if (options == null) {
        options = {};
      }
      out = fs.createWriteStream(dest, options);
      out.on('close', callback);
      out.on('error', callback);
      return readable_stream.pipe(out);
    };

    IOUtil.download_to_buffer = function(url, callback) {
      var params;
      params = {};
      if (typeof url === 'string') {
        params.url = url;
      } else {
        params = url;
      }
      params.encoding = null;
      return request(params, function(err, response, body) {
        if (typeof body === 'string') {
          body = new Buffer(body, 'binary');
        }
        if (err != null) {
          return callback(err);
        } else if (!/^2[0-9][0-9]$/.test("" + (response != null ? response.statusCode : void 0))) {
          return callback(new Error("Expected 2xx series status code for " + url + ", found " + (response != null ? response.statusCode : void 0) + "."), body, response);
        } else {
          return callback(null, body, response);
        }
      });
    };

    IOUtil.download_to_file = function(url, dest, options, callback) {
      var out, params;
      if ((options != null) && typeof options === 'function' && (callback == null)) {
        callback = options;
        options = null;
      }
      params = {};
      if (options == null) {
        options = {};
      }
      if (typeof url === 'string') {
        params.url = url;
      } else {
        params = url;
      }
      out = fs.createWriteStream(dest, options);
      out.on('close', callback);
      out.on('error', callback);
      return request(params).pipe(out);
    };

    IOUtil.download_to_data_uri = function(url, callback) {
      return IOUtil.download_to_buffer(url, function(err, buffer, response) {
        var data_uri, ref2;
        if (err != null) {
          return callback(err);
        } else if (buffer == null) {
          return callback(null, null);
        } else {
          data_uri = "data:";
          if ((response != null ? (ref2 = response.headers) != null ? ref2["content-type"] : void 0 : void 0) != null) {
            data_uri += response.headers["content-type"];
          }
          data_uri += ";base64,";
          data_uri += buffer.toString("base64");
          return callback(null, data_uri);
        }
      });
    };

    return IOUtil;

  })();

  exports.IOUtil = exports.IoUtil = IOUtil;

}).call(this);

//# sourceMappingURL=io-util.js.map
