// Generated by CoffeeScript 1.12.6
(function() {
  var ArrayUtil, Base64, ColorUtil, ComparatorUtil, DEBUG, DateUtil, ErrorUtil, HOMEDIR, IOUtil, IdUtil, LIB_COV, LIB_DIR, NumberUtil, ObjectUtil, PasswordUtil, RandomUtil, StringUtil, Util, WebUtil, crypto, fs, mkdirp, path, ref, ref1, remove, request, seedrandom, semver, uuid,
    slice = [].slice,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require('fs');

  path = require('path');

  HOMEDIR = path.join(__dirname, '..');

  LIB_COV = path.join(HOMEDIR, 'lib-cov');

  LIB_DIR = fs.existsSync(LIB_COV) ? LIB_COV : path.join(HOMEDIR, 'lib');

  ObjectUtil = require(path.join(LIB_DIR, 'object-util')).ObjectUtil;

  StringUtil = require(path.join(LIB_DIR, 'string-util')).StringUtil;

  uuid = require('uuid');

  crypto = require('crypto');

  mkdirp = require('mkdirp');

  request = require('request');

  remove = require('remove');

  seedrandom = require('seedrandom');

  semver = require('semver');

  DEBUG = (/(^|,)inote-?util($|,)/i.test(typeof process !== "undefined" && process !== null ? (ref = process.env) != null ? ref.NODE_DEBUG : void 0 : void 0)) || (/(^|,)Util($|,)/.test(typeof process !== "undefined" && process !== null ? (ref1 = process.env) != null ? ref1.NODE_DEBUG : void 0 : void 0));

  DateUtil = (function() {
    function DateUtil() {}

    DateUtil.DAY_OF_WEEK = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

    DateUtil.MONTH = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

    DateUtil.format_datetime_long = function(dt) {
      var e;
      if (dt == null) {
        dt = new Date();
      }
      if (typeof dt === 'string') {
        try {
          dt = new Date(dt);
        } catch (error) {
          e = error;
          return null;
        }
      }
      return (DateUtil.format_date_long(dt)) + " at " + (DateUtil.format_time_long(dt));
    };

    DateUtil.format_time_long = function(dt) {
      var ampm, hours, minutes;
      if (dt == null) {
        dt = new Date();
      }
      hours = dt.getUTCHours() % 12;
      if (hours === 0) {
        hours = 12;
      }
      minutes = dt.getUTCMinutes();
      if (minutes < 10) {
        minutes = "0" + minutes;
      }
      if (dt.getUTCHours() > 12) {
        ampm = "PM";
      } else {
        ampm = "AM";
      }
      return hours + ":" + minutes + " " + ampm + " GMT";
    };

    DateUtil.format_date_long = function(dt) {
      var e;
      if (dt == null) {
        dt = new Date();
      }
      if (typeof dt === 'string') {
        try {
          dt = new Date(dt);
        } catch (error) {
          e = error;
          return null;
        }
      }
      return DateUtil.DAY_OF_WEEK[dt.getUTCDay()] + " " + (dt.getUTCDate()) + " " + DateUtil.MONTH[dt.getUTCMonth()] + " " + (dt.getUTCFullYear());
    };

    DateUtil.to_unit = function(value, singular, plural) {
      if (plural == null) {
        plural = singular + "s";
      }
      if (value === 1 || value === -1) {
        return value + " " + singular;
      } else {
        return value + " " + plural;
      }
    };

    DateUtil.start_time = Date.now();

    DateUtil.duration = function(now, start) {
      var duration, i, j, k, len, len1, ref2, ref3, result, unit, v, values;
      if (start == null) {
        start = DateUtil.start_time;
      }
      if (now == null) {
        now = Date.now();
      }
      if (start instanceof Date) {
        start = start.getTime();
      }
      if (now instanceof Date) {
        now = now.getTime();
      }
      result = {};
      result.begin = start;
      result.end = now;
      result.delta = now - start;
      duration = result.delta;
      result.in_millis = {};
      result.in_millis.millis = duration % 1000;
      result.in_millis.seconds = duration % (1000 * 60);
      result.in_millis.minutes = duration % (1000 * 60 * 60);
      result.in_millis.hours = duration % (1000 * 60 * 60 * 24);
      result.in_millis.days = duration % (1000 * 60 * 60 * 24 * 7);
      result.in_millis.weeks = duration % (1000 * 60 * 60 * 24 * 7 * 52);
      result.in_millis.years = duration;
      result.raw = {};
      result.raw.millis = result.in_millis.millis;
      result.raw.seconds = result.in_millis.seconds / 1000;
      result.raw.minutes = result.in_millis.minutes / (1000 * 60);
      result.raw.hours = result.in_millis.hours / (1000 * 60 * 60);
      result.raw.days = result.in_millis.days / (1000 * 60 * 60 * 24);
      result.raw.weeks = result.in_millis.weeks / (1000 * 60 * 60 * 24 * 7);
      result.raw.years = result.in_millis.years / (1000 * 60 * 60 * 24 * 7 * 52);
      result.whole = {};
      result.whole.millis = Math.floor(result.raw.millis);
      result.whole.seconds = Math.floor(result.raw.seconds);
      result.whole.minutes = Math.floor(result.raw.minutes);
      result.whole.hours = Math.floor(result.raw.hours);
      result.whole.days = Math.floor(result.raw.days);
      result.whole.weeks = Math.floor(result.raw.weeks);
      result.whole.years = Math.floor(result.raw.years);
      result.array = {};
      result.array.full = {};
      result.array.full.values = [result.whole.years, result.whole.weeks, result.whole.days, result.whole.hours, result.whole.minutes, result.whole.seconds, result.whole.millis];
      result.array.full.short = [result.whole.years + "y", result.whole.weeks + "w", result.whole.days + "d", result.whole.hours + "h", result.whole.minutes + "m", result.whole.seconds + "s", result.whole.millis + "m"];
      result.array.full.long = [DateUtil.to_unit(result.whole.years, "year"), DateUtil.to_unit(result.whole.weeks, "week"), DateUtil.to_unit(result.whole.days, "day"), DateUtil.to_unit(result.whole.hours, "hour"), DateUtil.to_unit(result.whole.minutes, "minute"), DateUtil.to_unit(result.whole.seconds, "second"), DateUtil.to_unit(result.whole.millis, "millisecond")];
      result.array.full.no_millis = {};
      result.array.full.no_millis.values = [].concat(result.array.full.values.slice(0, -1));
      result.array.full.no_millis.short = [].concat(result.array.full.short.slice(0, -1));
      result.array.full.no_millis.long = [].concat(result.array.full.long.slice(0, -1));
      values = [].concat(result.array.full.values);
      while (values.length > 0 && values[0] === 0) {
        values.shift();
      }
      result.array.brief = {};
      result.array.brief.values = values;
      result.array.brief.short = [];
      result.array.brief.long = [];
      result.array.brief.no_millis = {};
      result.array.brief.no_millis.values = values.slice(0, -1);
      result.array.brief.no_millis.short = [];
      result.array.brief.no_millis.long = [];
      values = [].concat(values);
      ref2 = ['millisecond', 'second', 'minute', 'hour', 'day', 'week', 'year'];
      for (j = 0, len = ref2.length; j < len; j++) {
        unit = ref2[j];
        v = values.pop();
        if (v != null) {
          result.array.brief.short.unshift("" + v + (unit.substring(0, 1)));
          result.array.brief.long.unshift(DateUtil.to_unit(v, unit));
          if (unit !== 'millisecond') {
            result.array.brief.no_millis.short.unshift("" + v + (unit.substring(0, 1)));
            result.array.brief.no_millis.long.unshift(DateUtil.to_unit(v, unit));
          }
        } else {
          break;
        }
      }
      result.array.min = {};
      result.array.min.units = [];
      result.array.min.short = [];
      result.array.min.long = [];
      result.array.min.no_millis = {};
      result.array.min.no_millis.units = [];
      result.array.min.no_millis.short = [];
      result.array.min.no_millis.long = [];
      ref3 = ['year', 'week', 'day', 'hour', 'minute', 'second', 'millisecond'];
      for (i = k = 0, len1 = ref3.length; k < len1; i = ++k) {
        unit = ref3[i];
        v = result.array.full.values[i];
        if (v !== 0) {
          result.array.min.short.push("" + v + (unit.substring(0, 1)));
          result.array.min.long.push(DateUtil.to_unit(v, unit));
          result.array.min.units.push(unit);
          if (unit !== 'millisecond') {
            result.array.min.no_millis.short.push("" + v + (unit.substring(0, 1)));
            result.array.min.no_millis.long.push(DateUtil.to_unit(v, unit));
            result.array.min.no_millis.units.push(unit);
          }
        }
      }
      result.string = {};
      result.string.full = {};
      result.string.full.micro = result.array.full.short.join('');
      result.string.full.short = result.array.full.short.join(' ');
      result.string.full.long = result.array.full.long.join(' ');
      result.string.full.verbose = ArrayUtil.smart_join(result.array.full.long, ", ", " and ");
      result.string.full.no_millis = {};
      result.string.full.no_millis.micro = result.array.full.no_millis.short.join('');
      result.string.full.no_millis.short = result.array.full.no_millis.short.join(' ');
      result.string.full.no_millis.long = result.array.full.no_millis.long.join(' ');
      result.string.full.no_millis.verbose = ArrayUtil.smart_join(result.array.full.no_millis.long, ", ", " and ");
      result.string.brief = {};
      result.string.brief.micro = result.array.brief.short.join('');
      result.string.brief.short = result.array.brief.short.join(' ');
      result.string.brief.long = result.array.brief.long.join(' ');
      result.string.brief.verbose = ArrayUtil.smart_join(result.array.brief.long, ", ", " and ");
      result.string.brief.no_millis = {};
      result.string.brief.no_millis.micro = result.array.brief.no_millis.short.join('');
      result.string.brief.no_millis.short = result.array.brief.no_millis.short.join(' ');
      result.string.brief.no_millis.long = result.array.brief.no_millis.long.join(' ');
      result.string.brief.no_millis.verbose = ArrayUtil.smart_join(result.array.brief.no_millis.long, ", ", " and ");
      result.string.min = {};
      result.string.min.micro = result.array.min.short.join('');
      result.string.min.short = result.array.min.short.join(' ');
      result.string.min.long = result.array.min.long.join(' ');
      result.string.min.verbose = ArrayUtil.smart_join(result.array.min.long, ", ", " and ");
      result.string.min.no_millis = {};
      result.string.min.no_millis.micro = result.array.min.no_millis.short.join('');
      result.string.min.no_millis.short = result.array.min.no_millis.short.join(' ');
      result.string.min.no_millis.long = result.array.min.no_millis.long.join(' ');
      result.string.min.no_millis.verbose = ArrayUtil.smart_join(result.array.min.no_millis.long, ", ", " and ");
      return result;
    };

    DateUtil.iso_8601_regexp = function() {
      return /^((\d{4})-(\d{2})-(\d{2}))T((\d{2})\:(\d{2})\:((\d{2})(?:\.(\d{3}))?)((?:[A-Za-z]+)|(?:[+-]\d{2}\:\d{2})))$/;
    };

    return DateUtil;

  })();

  ArrayUtil = (function() {
    function ArrayUtil() {}

    ArrayUtil.lpad = StringUtil.lpad;

    ArrayUtil.lpad_array = StringUtil.lpad_array;

    ArrayUtil.rpad = StringUtil.rpad;

    ArrayUtil.rpad_array = StringUtil.rpad_array;

    ArrayUtil.smart_join = function(array, delimiter, last) {
      var after, before, buffer, first, head, j, k, middle, options, tail;
      if (array == null) {
        return null;
      } else {
        if (typeof delimiter === 'object') {
          options = delimiter;
          before = options.before;
          first = options.first;
          delimiter = options.delimiter;
          last = options.last;
          after = options.after;
        }
        if ((first != null) && (last != null)) {
          head = array[0], middle = 3 <= array.length ? slice.call(array, 1, j = array.length - 1) : (j = 1, []), tail = array[j++];
        } else if ((first != null) && (last == null)) {
          head = array[0], middle = 2 <= array.length ? slice.call(array, 1) : [];
        } else if ((last != null) && (first == null)) {
          middle = 2 <= array.length ? slice.call(array, 0, k = array.length - 1) : (k = 0, []), tail = array[k++];
        } else {
          middle = array;
        }
        if ((tail != null) && middle.length === 0) {
          middle = [tail];
          tail = void 0;
        }
        buffer = [];
        if (before != null) {
          buffer.push(before);
        }
        if (head != null) {
          buffer.push(head);
          if ((middle != null ? middle.length : void 0) > 0) {
            buffer.push(first);
          }
        }
        if (middle != null) {
          buffer.push(middle.join(delimiter));
        }
        if (tail != null) {
          if (last != null) {
            buffer.push(last);
          }
          buffer.push(tail);
        }
        if (after != null) {
          buffer.push(after);
        }
        return buffer.join("");
      }
    };

    ArrayUtil.trim_trailing_null = function(a) {
      var b, v;
      a = [].concat(a);
      b = [];
      while (a.length > 0) {
        v = a.pop();
        if (v != null) {
          b.unshift(v);
        } else if (b.length > 0) {
          b.unshift(v);
        }
      }
      return b;
    };

    ArrayUtil.right_shift_args = function() {
      var values;
      values = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return ArrayUtil.lpad(ArrayUtil.trim_trailing_null(values), values.length, null);
    };

    ArrayUtil.paginate_list = function(list, offset, limit) {
      if (offset == null) {
        offset = 0;
      }
      if (limit == null) {
        limit = 20;
      }
      return list.slice(offset, offset + limit);
    };

    ArrayUtil.subset_of = function(a, b) {
      var e, j, len;
      if (!((a != null) && Array.isArray(a) && (b != null) && Array.isArray(b))) {
        throw new Error("Expected arrays.");
      } else {
        for (j = 0, len = a.length; j < len; j++) {
          e = a[j];
          if (indexOf.call(b, e) < 0) {
            return false;
          }
        }
        return true;
      }
    };

    ArrayUtil.is_subset_of = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return ArrayUtil.subset_of.apply(ArrayUtil, args);
    };

    ArrayUtil.strict_subset_of = function(a, b) {
      return ArrayUtil.subset_of(a, b) && !ArrayUtil.subset_of(b, a);
    };

    ArrayUtil.is_strict_subset_of = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return ArrayUtil.strict_subset_of.apply(ArrayUtil, args);
    };

    ArrayUtil.sets_are_equal = function(a, b) {
      var e, j, k, len, len1;
      if (!((a != null) && Array.isArray(a) && (b != null) && Array.isArray(b))) {
        throw new Error("Expected arrays.");
      } else {
        for (j = 0, len = a.length; j < len; j++) {
          e = a[j];
          if (indexOf.call(b, e) < 0) {
            return false;
          }
        }
        for (k = 0, len1 = b.length; k < len1; k++) {
          e = b[k];
          if (indexOf.call(a, e) < 0) {
            return false;
          }
        }
        return true;
      }
    };

    ArrayUtil.arrays_are_equal = function(a, b) {
      if (!((a != null) && Array.isArray(a) && (b != null) && Array.isArray(b))) {
        throw new Error("Expected arrays.");
      } else {
        return ObjectUtil.deep_equal(a, b);
      }
    };

    ArrayUtil.uniquify = function(array, key) {
      var clone, elt, j, k, keys, len, len1, ref2;
      clone = [];
      if (key != null) {
        keys = [];
        for (j = 0, len = array.length; j < len; j++) {
          elt = array[j];
          if (ref2 = elt[key], indexOf.call(keys, ref2) < 0) {
            clone.push(elt);
            keys.push(elt[key]);
          }
        }
      } else {
        for (k = 0, len1 = array.length; k < len1; k++) {
          elt = array[k];
          if (indexOf.call(clone, elt) < 0) {
            clone.push(elt);
          }
        }
      }
      return clone;
    };

    return ArrayUtil;

  })();

  NumberUtil = (function() {
    function NumberUtil() {}

    NumberUtil.round_decimal = function(value, digits) {
      var factor;
      if (digits == null) {
        digits = 0;
      }
      if (value == null) {
        return null;
      } else {
        if (typeof value !== 'number') {
          if (/^\s*-?(([0-9]+(\.[0-9]+))|(\.[0-9]+))\s*$/.test("" + value)) {
            value = parseFloat(value);
          } else {
            return null;
          }
        }
        if (isNaN(value)) {
          return null;
        } else if (digits >= 0) {
          return value.toFixed(digits);
        } else {
          factor = Math.pow(10, Math.abs(digits));
          return "" + ((Math.round(value / factor)) * factor);
        }
      }
    };

    NumberUtil.is_int = function(v) {
      if (v == null) {
        return false;
      } else {
        return /^-?((0)|([1-9][0-9]*))$/.test("" + v);
      }
    };

    NumberUtil.to_int = function(v) {
      if (NumberUtil.is_int(v)) {
        v = parseInt(v);
        if (isNaN(v)) {
          return null;
        } else {
          return v;
        }
      } else {
        return null;
      }
    };

    NumberUtil.is_float = function(v) {
      if (v == null) {
        return false;
      } else {
        return /^-?((((0)|([1-9][0-9]*))(\.[0-9]+)?)|(\.[0-9]+))$/.test("" + v);
      }
    };

    NumberUtil.to_float = function(v) {
      if (NumberUtil.is_float(v)) {
        v = parseFloat(v);
        if (isNaN(v)) {
          return null;
        } else {
          return v;
        }
      } else {
        return null;
      }
    };

    return NumberUtil;

  })();

  ColorUtil = (function() {
    function ColorUtil() {}

    ColorUtil.hex_to_rgb_triplet = function(hex) {
      var result;
      result = /^\s*#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})\s*$/i.exec(hex);
      if (result != null) {
        return [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)];
      } else {
        return null;
      }
    };

    ColorUtil.hex_to_rgb_string = function(hex) {
      var b, g, r, ref2, ref3;
      ref3 = (ref2 = ColorUtil.hex_to_rgb_triplet(hex)) != null ? ref2 : [null, null, null], r = ref3[0], g = ref3[1], b = ref3[2];
      if ((r != null) && (g != null) && (b != null)) {
        return "rgb(" + r + "," + g + "," + b + ")";
      } else {
        return null;
      }
    };

    ColorUtil.rgb_string_to_triplet = function(rgb) {
      var b, g, r, result;
      result = /^\s*rgb\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)\s*$/i.exec(rgb);
      if (result != null) {
        r = parseInt(result[1]);
        g = parseInt(result[2]);
        b = parseInt(result[3]);
        return [r, g, b];
      } else {
        return null;
      }
    };

    ColorUtil.rgb_to_hex = function(r, g, b) {
      var i2h, ref2, ref3;
      if (typeof r === 'string' && (g == null) && (b == null)) {
        ref3 = (ref2 = ColorUtil.rgb_string_to_triplet(r)) != null ? ref2 : [null, null, null], r = ref3[0], g = ref3[1], b = ref3[2];
      }
      if (!((r != null) && (g != null) && (b != null))) {
        return null;
      } else {
        i2h = function(i) {
          var h;
          h = i.toString(16);
          if (h.length === 1) {
            return "0" + h;
          } else {
            return h;
          }
        };
        return "#" + (i2h(r)) + (i2h(g)) + (i2h(b));
      }
    };

    return ColorUtil;

  })();

  RandomUtil = (function() {
    function RandomUtil() {}

    RandomUtil.random_bytes = function(count, enc) {
      var bytes, ref2;
      if (count == null) {
        count = 32;
      }
      if (enc == null) {
        enc = 'hex';
      }
      if (typeof count === 'string') {
        if (typeof enc === 'number') {
          ref2 = [enc, count], count = ref2[0], enc = ref2[1];
        } else {
          enc = count;
          count = 32;
        }
      }
      bytes = crypto.randomBytes(count);
      if (/buffer/i.test(enc)) {
        return bytes;
      } else {
        return bytes.toString(enc);
      }
    };

    RandomUtil.seed_rng = function(seed) {
      return new Math.seedrandom(seed);
    };

    RandomUtil.set_rng = function(rng) {
      if (rng == null) {
        rng = Math.random;
      }
      return RandomUtil.rng = rng;
    };

    RandomUtil.rng = Math.random;

    RandomUtil.random_hex = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_digits(count, 16, rng);
    };

    RandomUtil.random_alphanumeric = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_digits(count, 36, rng);
    };

    RandomUtil.random_numeric = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_digits(count, 10, rng);
    };

    RandomUtil.random_Alpha = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_alpha(count, 'M', rng);
    };

    RandomUtil.random_ALPHA = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_alpha(count, 'U', rng);
    };

    RandomUtil.random_alpha = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil._random_alpha(count, 'L', rng);
    };

    RandomUtil.random_Alphanumeric = function(count, rng) {
      if (count == null) {
        count = 32;
      }
      return RandomUtil.random_string("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", count, rng);
    };

    RandomUtil.random_string = function(alphabet, count, rng) {
      var i, j, ref2, result;
      if (typeof alphabet === 'function' && (count == null) && (rng == null)) {
        rng = alphabet;
        count = null;
        alphabet = null;
      }
      if (typeof count === 'function' && (rng == null)) {
        rng = count;
        count = null;
      }
      if (typeof alphabet === 'number' && typeof count !== 'number') {
        count = alphabet;
        alphabet = null;
      }
      if (alphabet == null) {
        alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
      }
      if (count == null) {
        count = 32;
      }
      if (rng == null) {
        rng = RandomUtil.rng;
      }
      result = "";
      for (i = j = 0, ref2 = count; 0 <= ref2 ? j < ref2 : j > ref2; i = 0 <= ref2 ? ++j : --j) {
        result += alphabet[Math.floor(rng() * alphabet.length)];
      }
      return result;
    };

    RandomUtil._random_alpha = function(count, lettercase, rng) {
      var char, include_lower, include_upper, str;
      if (count == null) {
        count = 32;
      }
      if (lettercase == null) {
        lettercase = 'lower';
      }
      if (rng == null) {
        rng = RandomUtil.rng;
      }
      str = "";
      include_upper = /^(u|b|m)/i.test(lettercase);
      include_lower = !/^u/i.test(lettercase);
      while (str.length < count) {
        char = Math.floor(rng() * 26);
        if (include_upper && include_lower) {
          if (rng() > 0.5) {
            char += 97;
          } else {
            char += 65;
          }
        } else if (include_upper) {
          char += 65;
        } else {
          char += 97;
        }
        str += String.fromCharCode(char);
      }
      return str;
    };

    RandomUtil.random_element = function(collection, rng) {
      var index, key;
      if (collection == null) {
        return void 0;
      } else {
        if (Array.isArray(collection)) {
          if (!(collection.length > 0)) {
            return void 0;
          } else {
            if (rng == null) {
              rng = RandomUtil.rng;
            }
            index = Math.floor(rng() * collection.length);
            return collection[index];
          }
        } else if ((collection != null) && typeof collection === 'object') {
          key = RandomUtil.random_element(Object.keys(collection), rng);
          return [key, collection[key]];
        }
      }
    };

    RandomUtil._random_digits = function() {
      var a, args, base, count, ints, rng, str;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      ints = [];
      rng = null;
      while (args.length > 0) {
        a = args.shift();
        if (typeof a === 'function') {
          if (rng != null) {
            throw new Error("Unexpected arguments: " + args);
          } else {
            rng = a;
          }
        } else {
          if (ints.length === 2 && (a != null)) {
            throw new Error("Unexpected arguments: " + args);
          } else {
            ints.push(a);
          }
        }
      }
      count = ints[0], base = ints[1];
      if (count == null) {
        count = 32;
      }
      if (base == null) {
        base = 10;
      }
      if (rng == null) {
        rng = RandomUtil.rng;
      }
      str = "";
      while (str.length < count) {
        str += rng().toString(base).substring(2);
      }
      if (str.length > count) {
        str = str.substring(0, count);
      }
      return str;
    };

    return RandomUtil;

  })();

  PasswordUtil = (function() {
    function PasswordUtil() {}

    PasswordUtil.validate_hashed_password = function(expected_digest, password, salt, pepper, hash_type) {
      var digest, ref2;
      ref2 = PasswordUtil.hash_password(password, salt, pepper, hash_type), salt = ref2[0], digest = ref2[1];
      password = void 0;
      return Util.slow_equals(expected_digest, digest)[0];
    };

    PasswordUtil.hash_password = function(password, salt, pepper, hash_type) {
      var digest, hash;
      if (typeof password === 'object') {
        hash_type = password.hash_type;
        pepper = password.pepper;
        salt = password.salt;
        password = password.password;
      }
      if (hash_type == null) {
        hash_type = 'sha512';
      }
      if (salt == null) {
        salt = 64;
      }
      if ((password != null) && !Buffer.isBuffer(password)) {
        password = new Buffer(password);
      }
      if ((pepper != null) && !Buffer.isBuffer(pepper)) {
        pepper = new Buffer(pepper);
      }
      if (typeof salt === 'number') {
        salt = RandomUtil.random_bytes(salt, 'buffer');
      } else if (!Buffer.isBuffer(salt)) {
        salt = new Buffer(salt);
      }
      if (password == null) {
        throw new Error("password parameter is required");
      } else {
        hash = crypto.createHash(hash_type);
        hash.update(salt);
        if (pepper != null) {
          hash.update(pepper);
        }
        hash.update(password);
        password = void 0;
        digest = hash.digest();
        return [salt, digest];
      }
    };

    return PasswordUtil;

  })();

  ComparatorUtil = (function() {
    function ComparatorUtil() {}

    ComparatorUtil.slow_equals = function(a, b) {
      var delta_count, i, j, ref2, ref3, same_count;
      same_count = delta_count = 0;
      if (b.length > a.length) {
        ref2 = [b, a], a = ref2[0], b = ref2[1];
      }
      for (i = j = 0, ref3 = a.length; 0 <= ref3 ? j < ref3 : j > ref3; i = 0 <= ref3 ? ++j : --j) {
        if (a[i] !== b[i]) {
          delta_count += 1;
        } else {
          same_count += 1;
        }
      }
      if (delta_count === 0 && a.length === b.length) {
        return [true, same_count, delta_count];
      } else {
        return [false, same_count, delta_count];
      }
    };

    ComparatorUtil.compare = function(a, b) {
      var A, B, val;
      if ((a != null) && (b != null)) {
        if ((a.localeCompare != null) && (b.localeCompare != null) && (a.toUpperCase != null) && (b.toUpperCase != null)) {
          A = a.toUpperCase();
          B = b.toUpperCase();
          val = A.localeCompare(B);
          if (val === 0) {
            return a.localeCompare(b);
          } else {
            return val;
          }
        } else {
          return (a > b ? 1 : (a < b ? -1 : 0));
        }
      } else if ((a != null) && (b == null)) {
        return 1;
      } else if ((b != null) && (a == null)) {
        return -1;
      } else {
        return 0;
      }
    };

    ComparatorUtil.case_insensitive_compare = function(a, b) {
      return ComparatorUtil.compare(a, b);
    };

    ComparatorUtil.field_comparator = function(field, locale_compare) {
      if (locale_compare == null) {
        locale_compare = false;
      }
      return ComparatorUtil.path_comparator([field], locale_compare);
    };

    ComparatorUtil.path_comparator = function(path, locale_compare) {
      if (locale_compare == null) {
        locale_compare = false;
      }
      return function(a, b) {
        var A, B, f, fn, j, len;
        fn = null;
        if (locale_compare) {
          fn = Util.compare;
        } else {
          fn = function(a, b) {
            if ((a != null) && (b != null)) {
              return (a > b ? 1 : (a < b ? -1 : 0));
            } else if ((a != null) && (b == null)) {
              return 1;
            } else if ((b != null) && (a == null)) {
              return -1;
            } else {
              return 0;
            }
          };
        }
        A = a;
        B = b;
        for (j = 0, len = path.length; j < len; j++) {
          f = path[j];
          A = A != null ? A[f] : void 0;
          B = B != null ? B[f] : void 0;
          if (!((A != null) && (B != null))) {
            return fn(A, B);
          }
        }
        return fn(A, B);
      };
    };

    ComparatorUtil.desc_comparator = function(c) {
      return function(a, b) {
        return c(b, a);
      };
    };

    ComparatorUtil.descending_comparator = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return ComparatorUtil.desc_comparator.apply(ComparatorUtil, args);
    };

    ComparatorUtil.composite_comparator = function(list) {
      return function(a, b) {
        var c, j, len, r;
        for (j = 0, len = list.length; j < len; j++) {
          c = list[j];
          r = c(a, b);
          if (r !== 0) {
            return r;
          }
        }
        return 0;
      };
    };

    return ComparatorUtil;

  })();

  WebUtil = (function() {
    function WebUtil() {}

    WebUtil.remote_ip = function(req) {
      var ref10, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9;
      return (ref2 = (ref3 = (ref4 = (ref5 = req != null ? typeof req.get === "function" ? req.get('x-forwarded-for') : void 0 : void 0) != null ? ref5 : req != null ? (ref6 = req.headers) != null ? ref6['x-forwarded-for'] : void 0 : void 0) != null ? ref4 : req != null ? (ref7 = req.connection) != null ? ref7.remoteAddress : void 0 : void 0) != null ? ref3 : req != null ? (ref8 = req.socket) != null ? ref8.remoteAddress : void 0 : void 0) != null ? ref2 : req != null ? (ref9 = req.connection) != null ? (ref10 = ref9.socket) != null ? ref10.remoteAddress : void 0 : void 0 : void 0;
    };

    WebUtil.param = function(req, name, default_value) {
      var ref2, ref3, ref4, ref5, ref6, ref7;
      return (ref2 = req != null ? (ref3 = req.params) != null ? ref3[name] : void 0 : void 0) != null ? ref2 : (ref4 = req != null ? (ref5 = req.body) != null ? ref5[name] : void 0 : void 0) != null ? ref4 : (ref6 = req != null ? (ref7 = req.query) != null ? ref7[name] : void 0 : void 0) != null ? ref6 : default_value;
    };

    return WebUtil;

  })();

  IOUtil = (function() {
    function IOUtil() {}

    IOUtil.pipe_to_buffer = function(readable_stream, callback) {
      var data, length;
      data = [];
      length = 0;
      readable_stream.on('data', function(chunk) {
        if (chunk != null) {
          data.push(chunk);
          return length += chunk.length;
        }
      });
      readable_stream.on('error', function(err) {
        return callback(err);
      });
      return readable_stream.on('end', function() {
        return callback(null, Buffer.concat(data));
      });
    };

    IOUtil.pipe_to_file = function(readable_stream, dest, options, callback) {
      var out;
      if ((options != null) && typeof options === 'function' && (callback == null)) {
        callback = options;
        options = null;
      }
      out = fs.createWriteStream(dest, options);
      out.on('close', callback);
      out.on('error', callback);
      return readable_stream.pipe(out);
    };

    IOUtil.download_to_buffer = function(url, callback) {
      var params;
      params = {};
      if (typeof url === 'string') {
        params.url = url;
      } else {
        params = url;
      }
      return request(params, function(err, response, body) {
        if (err != null) {
          return callback(err);
        } else if (!/^2[0-9][0-9]$/.test(request != null ? request.statusCode : void 0)) {
          return callback(response, body);
        } else {
          return callback(null, body);
        }
      });
    };

    IOUtil.download_to_file = function(url, dest, options, callback) {
      var out, params;
      if ((options != null) && typeof options === 'function' && (callback == null)) {
        callback = options;
        options = null;
      }
      params = {};
      if (typeof url === 'string') {
        params.url = url;
      } else {
        params = url;
      }
      out = fs.createWriteStream(dest, options);
      out.on('close', callback);
      out.on('error', callback);
      return request(params).pipe(out);
    };

    return IOUtil;

  })();

  ErrorUtil = (function() {
    function ErrorUtil() {}

    ErrorUtil.handle_error = function(err, callback, throw_when_no_callback) {
      if (throw_when_no_callback == null) {
        throw_when_no_callback = true;
      }
      if (err != null) {
        if (callback != null) {
          callback(err);
          return true;
        } else if (throw_when_no_callback) {
          throw err;
        } else {
          return console.error("ERROR", err);
        }
      } else {
        return false;
      }
    };

    return ErrorUtil;

  })();

  IdUtil = (function() {
    function IdUtil() {}

    IdUtil.uuid = function(v, generate) {
      if (generate == null) {
        generate = false;
      }
      if (arguments.length === 0) {
        generate = true;
      }
      if (v == null) {
        if (generate) {
          v = IdUtil.uuid(uuid.v1());
        } else {
          return null;
        }
      } else if (v.replace == null) {
        throw new Error("Expected string but found " + (typeof v), v);
      } else if (!/^[0-9a-f]{8}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{4}-?[0-9a-f]{12}$/i.test(v)) {
        throw new Error("Encountered invalid UUID format " + v + ".");
      }
      return v.replace(/-/g, '').toLowerCase();
    };

    IdUtil.normalize_uuid = function(v, generate) {
      if (generate == null) {
        generate = false;
      }
      return IdUtil.uuid(v, generate);
    };

    IdUtil.make_uuid = function(v) {
      return IdUtil.uuid(v != null ? v : uuid.v1());
    };

    IdUtil.make_uuid_v1 = function(v) {
      return IdUtil.uuid(v != null ? v : uuid.v1());
    };

    IdUtil.make_uuid_v4 = function(v) {
      return IdUtil.uuid(v != null ? v : uuid.v4());
    };

    IdUtil.pad_uuid = function(v, generate) {
      if (generate == null) {
        generate = false;
      }
      v = IdUtil.uuid(v, generate);
      if (v != null) {
        return v.substring(0, 8) + "-" + v.substring(8, 12) + "-" + v.substring(12, 16) + "-" + v.substring(16, 20) + "-" + v.substring(20);
      } else {
        return null;
      }
    };

    return IdUtil;

  })();

  Base64 = (function() {
    function Base64() {}

    Base64.encode = function(buf, output_encoding) {
      if (output_encoding == null) {
        output_encoding = 'utf8';
      }
      if (buf == null) {
        return null;
      } else {
        if (!(buf instanceof Buffer)) {
          buf = new Buffer(buf.toString(), output_encoding);
        }
        return buf.toString('base64');
      }
    };

    Base64.decode = function(buf, output_encoding) {
      if (output_encoding == null) {
        output_encoding = 'utf8';
      }
      if (buf == null) {
        return null;
      } else {
        if (!(buf instanceof Buffer)) {
          buf = new Buffer(buf.toString(), 'base64');
        }
        return buf.toString(output_encoding);
      }
    };

    return Base64;

  })();

  Util = (function() {
    function Util() {}

    Util.version_satisfies = function(verstr, rangestr) {
      if (rangestr == null) {
        rangestr = verstr;
        verstr = null;
      }
      if (verstr == null) {
        verstr = process.version;
      }
      return semver.satisfies(verstr, rangestr);
    };

    Util.to_unit = DateUtil.to_unit;

    Util.start_time = DateUtil.start_time;

    Util.duration = DateUtil.duration;

    Util.iso_8601_regexp = DateUtil.iso_8601_regexp;

    Util.lpad_array = ArrayUtil.lpad_array;

    Util.rpad_array = ArrayUtil.rpad_array;

    Util.smart_join = ArrayUtil.smart_join;

    Util.trim_trailing_null = ArrayUtil.trim_trailing_null;

    Util.right_shift_args = ArrayUtil.right_shift_args;

    Util.paginate_list = ArrayUtil.paginate_list;

    Util.subset_of = ArrayUtil.subset_of;

    Util.is_subset_of = ArrayUtil.is_subset_of;

    Util.strict_subset_of = ArrayUtil.strict_subset_of;

    Util.is_strict_subset_of = ArrayUtil.is_strict_subset_of;

    Util.sets_are_equal = ArrayUtil.sets_are_equal;

    Util.arrays_are_equal = ArrayUtil.arrays_are_equal;

    Util.uniquify = ArrayUtil.uniquify;

    Util.round_decimal = NumberUtil.round_decimal;

    Util.is_int = NumberUtil.is_int;

    Util.to_int = NumberUtil.to_int;

    Util.is_float = NumberUtil.is_float;

    Util.to_float = NumberUtil.to_float;

    Util.is_decimal = NumberUtil.is_float;

    Util.to_decimal = NumberUtil.to_float;

    Util.remove_null = ObjectUtil.remove_null;

    Util.remove_falsey = ObjectUtil.remove_falsey;

    Util.merge = ObjectUtil.merge;

    Util.shallow_clone = ObjectUtil.shallow_clone;

    Util.object_array_to_map = ObjectUtil.object_array_to_map;

    Util.hex_to_rgb_triplet = ColorUtil.hex_to_rgb_triplet;

    Util.hex_to_rgb_string = ColorUtil.hex_to_rgb_string;

    Util.rgb_string_to_triplet = ColorUtil.rgb_string_to_triplet;

    Util.rgb_to_hex = ColorUtil.rgb_to_hex;

    Util.random_bytes = RandomUtil.random_bytes;

    Util.random_hex = RandomUtil.random_hex;

    Util.random_alphanumeric = RandomUtil.random_alphanumeric;

    Util.random_Alphanumeric = RandomUtil.random_Alphanumeric;

    Util.random_string = RandomUtil.random_string;

    Util.random_numeric = RandomUtil.random_numeric;

    Util.random_alpha = RandomUtil.random_alpha;

    Util.random_ALPHA = RandomUtil.random_ALPHA;

    Util.random_Alpha = RandomUtil.random_Alpha;

    Util.random_element = RandomUtil.random_element;

    Util.seed_rng = RandomUtil.seed_rng;

    Util.set_rng = RandomUtil.set_rng;

    Util.random_digits = RandomUtil._random_digits;

    Util.validate_hashed_password = PasswordUtil.validate_hashed_password;

    Util.hash_password = PasswordUtil.hash_password;

    Util.slow_equals = ComparatorUtil.slow_equals;

    Util.compare = ComparatorUtil.compare;

    Util.case_insensitive_compare = ComparatorUtil.case_insensitive_compare;

    Util.field_comparator = ComparatorUtil.field_comparator;

    Util.path_comparator = ComparatorUtil.path_comparator;

    Util.desc_comparator = ComparatorUtil.desc_comparator;

    Util.descending_comparator = ComparatorUtil.descending_comparator;

    Util.composite_comparator = ComparatorUtil.composite_comparator;

    Util.remote_ip = WebUtil.remote_ip;

    Util.handle_error = ErrorUtil.handle_error;

    Util.uuid = IdUtil.uuid;

    Util.pad_uuid = IdUtil.pad_uuid;

    Util.b64e = Base64.encode;

    Util.b64d = Base64.decode;

    return Util;

  })();

  exports.ArrayUtil = ArrayUtil;

  exports.Base64 = Base64;

  exports.ColorUtil = ColorUtil;

  exports.ComparatorUtil = ComparatorUtil;

  exports.DateUtil = DateUtil;

  exports.ErrorUtil = ErrorUtil;

  exports.IdUtil = IdUtil;

  exports.MapUtil = ObjectUtil;

  exports.NumberUtil = NumberUtil;

  exports.PasswordUtil = PasswordUtil;

  exports.RandomUtil = RandomUtil;

  exports.StringUtil = StringUtil;

  exports.Util = Util;

  exports.WebUtil = WebUtil;

}).call(this);
